config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :infos do
    member {get :img}
  end
  resources :calendars
  resources :gifts do
    member {get :img}
    member {get :eval}
  end
  resources :questions
  resources :anstoevals

  get '/admin' => 'welcome#admin'

  get '/qflow' => 'qflow#index'
  get '/qflow_continue' => 'qflow#continue'
  post '/result' => 'result#index'
  get '/result/countup' => 'result#countup'
  get '/result/countdown' => 'result#countdown'
  get '/result/countdown2' => 'result#countdown2'
  get '/new_arrival' => 'welcome#new'
  get '/info' => 'welcome#info'
  
  get '/calendar/getevent' => 'calendars#getevent'
  get '/calendar/search' => 'calendars#search'
  get '/calendar/ajaxcreate' => 'calendars#ajaxcreate'
  get '/calendar/daynameconf' => 'calendars#daynameconf'
  get '/calendar/nearday' => 'calendars#nearday'
  get '/calendar/search_bud' => 'calendars#search_bud'
  get '/calendar/search_flower' => 'calendars#search_flower'
  get '/calendar/eval' => 'calendars#eval'
  get '/calendar/get_calendar' => 'calendars#get_calendar'
  

  root 'welcome#index'
  
    post 'linebot/callback' => 'webhook#callback'
    post '/fbbot/callback' => 'fbmessenger#callback'

end

app/models/anstoeval.rb
class Anstoeval < ActiveRecord::Base
  belongs_to :answer
  belongs_to :evaluation
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :gift
end

app/models/fbtalk.rb
class Fbtalk < ActiveRecord::Base
end

app/models/gift.rb
class Gift < ActiveRecord::Base
    validates :name,
      presence: true,
      uniqueness: true
    validates :url,
      presence: true,
      uniqueness: true
    validates :img,
      presence: true
    validates :company_name,
      presence: true
    validates :price,
      presence: true
end

app/models/giftcalendar.rb
class Giftcalendar < ActiveRecord::Base
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
    validates :body,
      presence: true
end

app/models/talk.rb
class Talk < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  
  before_action do
    PERMIT_ADDRESSES = ['127.0.0.1', '::1', '115.165.80.15' , ENV['MY_IP_ADDRESS'], ENV['MY_SUB_IP_ADDRESS'], ENV['H_IP_ADDRESS']].freeze

    unless PERMIT_ADDRESSES.include?(request.remote_ip)
      render text: 'Service Unavailable', status: 503
    end
  end
  
  layout 'home'

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.order(:id)
   
    @qYes = Hash.new(0)
    @qNo  = Hash.new(0)
    
    @questions.each do |question|
      yes=Answer.where(:question_id => question.id).find_by_ansid(1) || Answer.create(question_id: question.id , ansid: 1 , count: 0)
      no =Answer.where(:question_id => question.id).find_by_ansid(2) || Answer.create(question_id: question.id , ansid: 2 , count: 0)
      @qYes[question]= yes.count
      @qNo[question]=  no.count 
    end

  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:body)
    end
end

app/helpers/anstoevals_helper.rb
module AnstoevalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/fbmessenger_helper.rb
module FbmessengerHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/qflow_helper.rb
module QflowHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <script src="/bootstrap/js/bootstrap.min.js"></script>

<p id="notice"><%= notice %></p>

<a href="/admin">Admin Home</a>

<h1>Listing Questions</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Body</th>
      <th>Yesの回数</th>
      <th>Noの回数</th>
      <th>Yesの割合</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.body %></td>
        <td><%= @qYes[question] %></td>
        <td><%= @qNo[question] %></td>
        <td><%= 1.0*@qYes[question]/(@qYes[question]+@qNo[question]) %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>
<%= link_to 'New Question', new_question_path %>