config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :infos do
    member {get :img}
  end
  resources :calendars
  resources :gifts do
    member {get :img}
    member {get :eval}
  end
  resources :questions
  resources :anstoevals

  get '/admin' => 'welcome#admin'

  get '/qflow' => 'qflow#index'
  get '/qflow_continue' => 'qflow#continue'
  post '/result' => 'result#index'
  get '/result/countup' => 'result#countup'
  get '/result/countdown' => 'result#countdown'
  get '/result/countdown2' => 'result#countdown2'
  get '/new_arrival' => 'welcome#new'
  get '/info' => 'welcome#info'
  
  get '/calendar/getevent' => 'calendars#getevent'
  get '/calendar/search' => 'calendars#search'
  get '/calendar/ajaxcreate' => 'calendars#ajaxcreate'
  get '/calendar/daynameconf' => 'calendars#daynameconf'
  get '/calendar/nearday' => 'calendars#nearday'
  get '/calendar/search_bud' => 'calendars#search_bud'
  get '/calendar/search_flower' => 'calendars#search_flower'
  get '/calendar/eval' => 'calendars#eval'
  get '/calendar/get_calendar' => 'calendars#get_calendar'
  

  root 'welcome#index'
  
    post 'linebot/callback' => 'webhook#callback'
    post '/fbbot/callback' => 'fbmessenger#callback'

end

app/models/anstoeval.rb
class Anstoeval < ActiveRecord::Base
  belongs_to :answer
  belongs_to :evaluation
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :gift
end

app/models/fbtalk.rb
class Fbtalk < ActiveRecord::Base
end

app/models/gift.rb
class Gift < ActiveRecord::Base
    validates :name,
      presence: true,
      uniqueness: true
    validates :url,
      presence: true,
      uniqueness: true
    validates :img,
      presence: true
    validates :company_name,
      presence: true
    validates :price,
      presence: true
end

app/models/giftcalendar.rb
class Giftcalendar < ActiveRecord::Base
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
    validates :body,
      presence: true
end

app/models/talk.rb
class Talk < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy, :img]
  before_action :restrict_remote_ip, except: [:img]
  
  PERMIT_ADDRESSES = ['127.0.0.1', '::1', '119.104.107.144' ,ENV['MY_IP_ADDRESS'], ENV['MY_SUB_IP_ADDRESS'], ENV['H_IP_ADDRESS']]
  
  layout 'home'
  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.order(:id)
    
    @giftEval1 = Hash.new()
    @giftEval2 = Hash.new()
    
    @gifts.each do |gift|
      eval1=Evaluation.where(:gift_id => gift.id).find_by_evalid(1) || Evaluation.create(gift_id: gift.id , evalid: 1 ,count: 0)
      eval2=Evaluation.where(:gift_id => gift.id).find_by_evalid(2) || Evaluation.create(gift_id: gift.id , evalid: 2 ,count: 0)
      @giftEval1[gift]=eval1.count
      @giftEval2[gift]=eval2.count
    end
    
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)
    #画像が登録されていなかったらid１の画像を設定する
    if params[:gift][:img] !=nil
      @gift.img = params[:gift][:img].read # <= バイナリをセット
      @gift.img_content_type = params[:gift][:img].content_type # <= ファイルタイプをセット
    else
      @gift.img = Gift.find(1).img
      @gift.img_content_type = Gift.find(1).img_content_type
    end

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        if params[:gift][:img] !=nil
          @gift.update(:img => params[:gift][:img].read) # <= バイナリをセット
          @gift.update(:img_content_type => params[:gift][:img].content_type) # <= ファイルタイプをセット
        else
          # @gift.update(:img => Gift.find(1).img) # <= バイナリをセット
          # @gift.update(:img_content_type => Gift.find(1).img_content_type) # <= ファイルタイプをセット
        end
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def img
  send_data(@gift.img, type: @gift.img_content_type, disposition: :inline)
  end
  
  def eval
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:name,:url,:company_name,:price)
    end
    
    def restrict_remote_ip
    unless PERMIT_ADDRESSES.include?(request.remote_ip)
      render text: 'Service Unavailable', status: 503
    end
    end
end

app/helpers/anstoevals_helper.rb
module AnstoevalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/fbmessenger_helper.rb
module FbmessengerHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/qflow_helper.rb
module QflowHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :img %><br>
    <%= f.file_field :img %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <p><strong>1: ～2000円</strong></p>
  <p><strong>2: 2000円～5000円</strong></p>
  <p><strong>3  5000円～10000円</strong></p>
  <p><strong>4: 10000円～30000円</strong></p>
  <p><strong>5: 30000円～</strong></p>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <script src="/bootstrap/js/bootstrap.min.js"></script>


<p id="notice"><%= notice %></p>

<a href="/admin">Admin Home</a>

<h1>Listing Gifts</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Url</th>
      <th>Img</th>
      <th>Img content type</th>
      <th>Company Name</th>
      <th>Price</th>
      <th>Dislikeの回数</th>
      <th>Likeの回数</th>
      <th>Likeの割合</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= gift.id %></td>
        <td><%= gift.name %></td>
        <td><%= gift.url[0,10]+"..." %></td>
        <td><%= image_tag(img_gift_path(gift), :height => "100px") %></td>
        <td><%= gift.img_content_type %></td>
        <td><%= gift.company_name %></td>
        <td><%= gift.price %></td>
        <td><%= @giftEval1[gift] %></td>
        <td><%= @giftEval2[gift] %></td>
        <td><%= 1.0*@giftEval2[gift]/(@giftEval1[gift]+@giftEval2[gift]) %></td>
        <td><%= link_to 'Show', gift %></td>
        <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
        <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<h1>New Gift</h1>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gift.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @gift.url %>
</p>

<p>
  <strong>Img:</strong>
  <%= image_tag(img_gift_path(@gift), :height => "100px") %>
</p>

<p>
  <strong>Img content type:</strong>
  <%= @gift.img_content_type %>
</p>

<p>
  <strong>Company Bame:</strong>
  <%= @gift.company_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @gift.price %>
</p>



<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>
<%= link_to 'New Gift', new_gift_path %>