config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :infos do
    member {get :img}
  end
  resources :calendars
  resources :gifts do
    member {get :img}
    member {get :eval}
  end
  resources :questions
  resources :anstoevals

  get '/admin' => 'welcome#admin'

  get '/qflow' => 'qflow#index'
  get '/qflow_continue' => 'qflow#continue'
  post '/result' => 'result#index'
  get '/result/countup' => 'result#countup'
  get '/result/countdown' => 'result#countdown'
  get '/result/countdown2' => 'result#countdown2'
  get '/new_arrival' => 'welcome#new'
  get '/info' => 'welcome#info'
  
  get '/calendar/getevent' => 'calendars#getevent'
  get '/calendar/search' => 'calendars#search'
  get '/calendar/ajaxcreate' => 'calendars#ajaxcreate'
  get '/calendar/daynameconf' => 'calendars#daynameconf'
  get '/calendar/nearday' => 'calendars#nearday'
  get '/calendar/search_bud' => 'calendars#search_bud'
  get '/calendar/search_flower' => 'calendars#search_flower'
  get '/calendar/eval' => 'calendars#eval'
  get '/calendar/get_calendar' => 'calendars#get_calendar'
  

  root 'welcome#index'
  
    post 'linebot/callback' => 'webhook#callback'
    post '/fbbot/callback' => 'fbmessenger#callback'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
   before_action do
        #端末によってViewファイルを振り分ける
        if (request.user_agent.include?("Mobile") || request.user_agent.include?("iPhone")) || request.user_agent.include?("Android") then
            request.variant = :mobile
        else
        end
        # case params[:device]
        # when 'tablet'
        #   request.variant = :tablet
        # when 'mobile'
        #   request.variant = :mobile
        # end
    end

  # GET /calendars
  # GET /calendars.json
  def index
    # @calendars = Calendar.all
    
    render :layout => 'home'
  end
  
  #************************Ajax****************************
  
  #当日に近いギフト・デイを探す
  def nearday
    dayIndex=params[:index].to_i
    
    @calendars = Giftcalendar.where(judge_num: 1)
    
    dayIndex=dayIndex%@calendars.length
    
    
    #keyがカレンダーでバリューが今日の日付からの差
    @calHash = Hash.new(0)
    
    #今年
    @thisYear=Date.today.year
    @today=Date.today
    
    @calendars.each do |cal|
        begin
          @konohi=Date.new(cal.year.to_i ,cal.month.to_i ,cal.day.to_i)
        rescue => e
        logger.error e
        logger.error e.backtrace.join("\n")
        end
        orderNum=(@konohi-@today).to_i
        @calHash[cal]=orderNum
    end
    
    @nearestDay= @calHash.sort_by{|key, value| value}[dayIndex][0]
    @length= @calHash.sort_by{|key, value| value}[dayIndex][1]
    
    render text: '	<div class="nearday_date">'+@nearestDay.year.to_s+'年'+@nearestDay.month.to_s+'月'+@nearestDay.day.to_s+'日</div>
		<div class="nearday_name"><h3><strong>'+@nearestDay.name+'</strong></h3></div>
		<div class="nearday_for_text"><h4>'+@nearestDay.for_whom+'に</h4></div>
		<div class="nearday_for">プレゼントを渡そう!!</div>'
  end
  
  #芽を探す
  def search_bud
    searchWord  = params[:searchword]
    searchWordArray = searchWord.split(",")
    fromYear = params[:fromyear].to_i
    fromMonth = params[:frommonth].to_i
    fromDay = params[:fromday].to_i
    toYear = params[:toyear].to_i
    toMonth = params[:tomonth].to_i
    toDay = params[:today].to_i
    
    if toYear==0 && toMonth==0 && toDay==0 then
      toYear = 2999
      toMonth = 12
      toDay = 31
    end
    
    @calendars = Giftcalendar.order('year,month,day')
    
    @calendars = @calendars.where('year >= ?', fromYear)
    @calendars = @calendars.where('month >= ?', fromMonth)
    @calendars = @calendars.where('day >= ?', fromDay)
    @calendars = @calendars.where('year <= ?', toYear)
    @calendars = @calendars.where('month <= ?', toMonth)
    @calendars = @calendars.where('day <= ?', toDay)
    
    # @calendars = @calendars.where(judge_num: 0)
    
    searchWordArray.each do |swa|
      @calendars=@calendars.where("name like '%" + swa + "%' OR for_whom like '%" + swa +"%'")
    end
    responseText=""
    if @calendars.empty? then
      responseText="<div>該当する結果はありません</div>"
    else
      num = @calendars.count
      #responseText="<div class='gdtitle'>該当するギフトデーが"+num.to_s+"件あります</div>"
      @calendars.each do |cal|
        responseText+='<div class="day_contents_container"><div class="share">
    <div class="share-box"><a class="share-button twitter" href="http://twitter.com/intent/tweet?text='+cal.month.to_s+'月'+cal.day.to_s+'日は'+cal.name+'&url=https://mocca-giftfinder.herokuapp.com" onclick="window.open(encodeURI(decodeURI(this.href)), "tweetwindow", "width=550, height=450, personalbar=0, toolbar=0, scrollbars=1, resizable=1" ); return false;" target="_blank"><i class="fontawesome-twitter"></i>ツイート</a></div>
    <div class="share-box"><a class="share-button facebook" href="http://www.facebook.com/share.php?u=https://mocca-giftfinder.herokuapp.com" onclick="window.open(this.href, "window", "width=550, height=450,personalbar=0,toolbar=0,scrollbars=1,resizable=1"); return false;"><i class="fontawesome-facebook"></i>シェア</a></div>
    <div class="share-box"><a class="share-button line" href="http://line.me/R/msg/text/?'+cal.month.to_s+'月'+cal.day.to_s+'日は'+cal.name+'">LINE</a></div>
    <div class="share-box"><a class="share-button googleCalendar" href="https://www.google.com/calendar/gp?pli=1#~calendar:view=e&bm=1&action=TEMPLATE&text='+cal.name+'&dates='+Date.new(cal.year.to_i,cal.month.to_i,cal.day.to_i).strftime("%Y%m%d")+'/'+Date.new(cal.year.to_i,cal.month.to_i,cal.day.to_i).strftime("%Y%m%d")+'&location=&trp=true&trp=undefined&trp=true&sprop="></a></div>
</div><div class="day_contents type'+cal.judge_num.to_s+'">
				<div class="day_date">'+cal.month.to_s+'月'+cal.day.to_s+'日</div>
				<div class="day_name">'+cal.name+'</div>
				<div class="day_concept">'+cal.concept+'</div>
				<div class="day_for_title">こんな人にプレゼントを渡そう!!</div>
				<div class="day_for">'+cal.for_whom+'</div>
				<div class="day_evals">
				    <div class="day_eval" id="like_eval">
						<a href="javascript:void(0);" class="day_evalbtn cal_eval_like'+cal.id.to_s+'" id="likebtn" onclick="evalup('+cal.id.to_s+');"></a>
						<div class="day_evalnum cal_like'+cal.id.to_s+'" id="likenum">'+cal.like_count.to_s+'</div>
					</div>
					<div class="day_eval" id="dislike_eval">
						<a href="javascript:void(0);" class="day_evalbtn cal_eval_dislike'+cal.id.to_s+'" id="dislikebtn" onclick="evaldown('+cal.id.to_s+');"></a>
						<div class="day_evalnum cal_dislike'+cal.id.to_s+'" id="dislikenum">'+cal.dislike_count.to_s+'</div>
				    </div>	
				</div>
			</div></div>'
      end
    end
    render text: responseText
  end
  
  def search_flower
    searchWord  = params[:searchword]
    searchWordArray = searchWord.split(",")
    @calendars = Giftcalendar.order('month,day')
    @calendars = @calendars.where(judge_num: 1)
    searchWordArray.each do |swa|
      @calendars=@calendars.where("name like '%" + swa + "%' OR for_whom like '%" + swa +"%'")
    end
    responseText=""
    if @calendars.empty? then
      responseText="<div>該当する結果はありません</div>"
    else
      num = @calendars.count
      #responseText="<div class='gdtitle'>該当するギフトデーが"+num.to_s+"件あります</div>"
      @calendars.each do |cal|
        responseText+='<div class="day_contents">
				<div class="day_date">'+cal.month.to_s+'月'+cal.day.to_s+'日</div>
				<div class="day_name">'+cal.name+'</div>
				<div class="day_concept">'+cal.concept+'</div>
				<div class="day_for_title">こんな人にプレゼントを渡そう!!</div>
				<div class="day_for">'+cal.for_whom+'</div>
				<div class="day_evals">
				    <div class="day_eval" id="like_eval">
						<a href="javascript:void(0);" class="day_evalbtn cal_eval_like'+cal.id.to_s+'" id="likebtn" onclick="evalup('+cal.id.to_s+');"></a>
						<div class="day_evalnum cal_like'+cal.id.to_s+'" id="likenum">'+cal.like_count.to_s+'</div>
					</div>
					<div class="day_eval" id="dislike_eval">
						<a href="javascript:void(0);" class="day_evalbtn cal_eval_dislike'+cal.id.to_s+'" id="dislikebtn" onclick="evaldown('+cal.id.to_s+');"></a>
						<div class="day_evalnum cal_dislike'+cal.id.to_s+'" id="dislikenum">'+cal.dislike_count.to_s+'</div>
				    </div>	
				</div>
			</div>'
      end
    end
    render text: responseText
  end
  
  
  def eval
    @limit_num=5
    index=params[:index].to_i
    type=params[:type]
    case type
    when "up" then
      @calendar=Giftcalendar.find(index)
      @calendar.update(like_count: @calendar.like_count.to_i+1)
      if @calendar.like_count==@limit_num then
        @calendar.update(judge_num: 1)
        responseText=@calendar.like_count.to_s
      else
        responseText=@calendar.like_count.to_s
      end
    when "down" then
      @calendar=Giftcalendar.find(index)
      @calendar.update(dislike_count: @calendar.dislike_count.to_i+1)
      disNum=@calendar.dislike_count.to_i
      if @calendar.judge_num==0 && @calendar.dislike_count==@limit_num then
        @calendar.destroy
        responseText=disNum.to_s
      else
        responseText=@calendar.dislike_count.to_s
      end
    else
    end
    render text: responseText
  end
  
    

  
  def getevent
    month=params[:month]
    day=params[:day]
    @calendars=Calendar.where(month: month, day: day)
    responseText="<div>"+month+"月"+day+"日は...</div>"
    if Calendar.where(month: month, day: day).empty? then
      responseText+="まだギフトデーが登録されていません..."
    else
      @calendars.each do |cal|
        responseText+="<div class='gddata'><p><strong>"+cal.name1+"</strong></p><p>For "+cal.name2+"</p><p class='datestr'></div>"
      end
    end
    render text: responseText
  end
  
  def search
    searchWord  = params[:searchword]
    searchWordArray = searchWord.split(",")
    @calendars = Calendar.all
    searchWordArray.each do |swa|
      @calendars=@calendars.where("name1 like '%" + swa + "%' OR name2 like '%" + swa +"%'")
    end
    
    if @calendars.empty? then
      responseText="該当する結果はありません"
    else
      num = @calendars.count
      responseText="<div class='gdtitle'>該当するギフトデーが"+num.to_s+"件あります</div>"
      @calendars.each do |cal|
        responseText+="<div class='gddata'><p><strong>"+cal.name1+"</strong></p><p>For "+cal.name2+"</p><p class='datestr'>"+cal.month.to_s+"月"+cal.day.to_s+"日</p></div>"
      end
    end
    
    render text: responseText
  end
  
  def ajaxcreate
    dayName = params[:dayname]
    forWhom = params[:forwhom]
    concept = params[:concept]
    year = params[:year]
    month = params[:month]
    day = params[:day]
    if forWhom!="" && dayName!="" && year!="" && month!="" && day!="" then
      Giftcalendar.create(year: year, month: month, day: day, name: dayName, for_whom: forWhom, concept: concept, judge_num: 0 , like_count: 0 , dislike_count: 0)
      responseText="<div><strong>日付:</strong></div>
                      <div>"+year.to_s+"年"+month.to_s+"月"+day.to_s+"日</div>
                    <div><strong>名称:</strong></div>
                      <div>"+dayName+"</div>
                    <div><strong>プレゼントを渡す相手:</strong></div>
                      <div>"+forWhom+"</div>

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.number_field :day %>
  </div>
  <div class="field">
    <%= f.label :name1 %><br>
    <%= f.text_field :name1 %>
  </div>
  <div class="field">
    <%= f.label :name2 %><br>
    <%= f.text_field :name2 %>
  </div>
  <div class="field">
    <%= f.label :name3 %><br>
    <%= f.text_field :name3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html1+mobile.erb
		<script>
			$(function(){
				$('.addnew_button').on('click', function(){
					$('.searching').fadeOut();
					$('.addnew_button').fadeOut();
					$('.addnew').fadeIn();
				});
				$('.close_button').on('click', function(){
					$('.addnew').fadeOut();
					$('.searching').fadeIn();
					$('.addnew_button').fadeIn();
					$('#create_form input').val("");
					$('#create_form span').html("");
					$('#create_form input').removeClass("checked");
				});
				
				$('.search_button').on('click',function(){
					searchWord = $('#search_form [name=searchWord]').val();
					searchWordArray = searchWord.replace("　", " ").replace(/\s+/g," ").split(" ");
					searchWordWithoutSpace = searchWordArray.join(",");
					$('.for_search').slideDown();
					// $('.result').html(searchWordWithoutSpace);
					$.ajax({
								type: 'GET',
								url: '/calendar/search',
								data: {
									searchword: searchWordWithoutSpace
								},
								dataType: 'text'
							})
							.done(function( data, textStatus, jqXHR ) {
							        $('.result').html(data);
							})
							.fail(function( jqXHR, textStatus, errorThrown ) {
							       
							})
							.always(function( jqXHR, textStatus ) {
							        
							});
				});
				
				$("#search_form").keypress(function(ev) {
					if ((ev.which && ev.which === 13) || (ev.keyCode && ev.keyCode === 13)) {
						searchWord = $('#search_form [name=searchWord]').val();
						searchWordArray = searchWord.replace("　", " ").replace(/\s+/g," ").split(" ");
						searchWordWithoutSpace = searchWordArray.join(",");
						$.ajax({
							type: 'GET',
							url: '/calendar/search',
							data: {
								searchword: searchWordWithoutSpace
							},
							dataType: 'text'
						})
						.done(function( data, textStatus, jqXHR ) {
						        $('.result').html(data);
						})
						.fail(function( jqXHR, textStatus, errorThrown ) {
						       
						})
						.always(function( jqXHR, textStatus ) {
						        
						});
						return false;
					} else {
						return true;
					}
				});
				
				// $(".submit_button").prop('disabled', true);
				
				$("#dayName").keyup(function(ev) {
					    dayName = $('#create_form [name=dayName]').val();
						$.ajax({
							type: 'GET',
							url: '/calendar/daynameconf',
							data: {
								dayname: dayName
							},
							dataType: 'text'
						})
						.done(function( data, textStatus, jqXHR ) {
						        if(data=="true"){
						        	$('#dncheck').html('<i class="glyphicon glyphicon-ok-circle" style="color:blue;"></i>');
						        	$('#dayName').addClass('checked');
						        	$('.create_result').html("");
						        } else {
						        	$('#dncheck').html('<i class="glyphicon glyphicon-remove-circle" style="color:red;"></i>');
						        	$('#dayName').removeClass('checked');
						        	$('.create_result').html("この名称のギフトデーは既に登録されています");
						        }
						})
						.fail(function( jqXHR, textStatus, errorThrown ) {
						       
						})
						.always(function( jqXHR, textStatus ) {
						        
						});
				});
				
				$("#month , #day").on('click keyup',function(ev){
					month = $('#create_form [name=month]').val();
					day = $('#create_form [name=day]').val();
					monthNum = parseInt(month,10);
					dayNum = parseInt(day,10);
					
					function ValidDate(y,m,d) {
						dt=new Date(y,m-1,d);
						return(dt.getFullYear()==y && dt.getMonth()==m-1 && dt.getDate()==d);
					}
					
					if(ValidDate(2016,monthNum,dayNum)) {
						$('#datecheck').html('<i class="glyphicon glyphicon-ok-circle" style="color:blue;"></i>');
						$('#month').addClass('checked');
						$('#day').addClass('checked');
						$('.create_result').html("");
					} else {
						$('#datecheck').html('<i class="glyphicon glyphicon-remove-circle" style="color:red;"></i>');
						$('#month').removeClass('checked');
						$('#day').removeClass('checked');
						$('.create_result').html("日付が不正です");
					}
				});
				
				$('#forWhom').keyup(function(){
					forWhom = $('#create_form [name=forWhom]').val();
					if(forWhom=="") {
						$('#fwcheck').html('<i class="glyphicon glyphicon-remove-circle" style="color:red;"></i>');
						$('#forWhom').removeClass('checked');
						$('.create_result').html("プレゼントを渡す相手を設定してください");
					} else {
						$('#fwcheck').html('<i class="glyphicon glyphicon-ok-circle" style="color:blue;"></i>');
						$('#forWhom').addClass('checked');
						$('.create_result').html("");
					}
				});
				
					
				
				$("body").on("click keyup",function(){
				    var checked_num = $('.checked').length;
				    // console.log(checked_num);
					if(checked_num <= 3){
						$('.submit_button').off('click');
						$('.submit_button').css("display","none");
				    } else {
				    	$('.submit_button').css("display","block");
				    	$('.submit_button').off('click').on('click',function(){
						dayName = $('#create_form [name=dayName]').val();
						forWhom = $('#create_form [name=forWhom]').val();
						month = $('#create_form [name=month]').val();
						day = $('#create_form [name=day]').val();
						
						$.ajax({
									type: 'GET',
									url: '/calendar/ajaxcreate',
									data: {
										dayname: dayName,
										forwhom: forWhom,
										month: month,
										day: day
									},
									dataType: 'text'
								})
								.done(function( data, textStatus, jqXHR ) {
									if(data=="登録に失敗しました") {
										$('.create_result').append("\n"+data);
									} else {
								        $('.result').html(data);
								        $('.addnew').fadeOut();
										$('.searching').fadeIn();
										$('.addnew_button').fadeIn();
										$('#create_form input').val("");
										$('#create_form input').removeClass("checked");
										$('#create_form span').html("");
									}
								})
								.fail(function( jqXHR, textStatus, errorThrown ) {
								       
								})
								.always(function( jqXHR, textStatus ) {
								        
								});
					    });
				    }
			    });
				
				
			})
		</script>
		<style>
	
		  .space {
		  	width: 100%;
		  	height: 100%;
		  	/*border: solid 1px;*/
		  	padding: 3px;
		  	/*overflow: scroll;*/
		  	/*background-color: white;*/
		  }
		  .search {
		  	position: relative;
		  	height: 38px;
		  	border-bottom: double 5px;
		  }
		  .search input {
		  	margin-left: 10px;
		  	margin-top: 5px;
		  }
		  .search_button {
		  	display: block;
		  	height:26px;
		  	width: 26px;
		  	position: absolute;
		  	top: 0px;
		  	right: 10px;
		  	background-size: cover;
		  	background-position: center;
		  	background-image: url('/image/search.png');
		  }
		  
		  .result_space {
		  	width: 95%;
		  	margin: auto;
		  	margin-top: 5px;
		  	height: 355px;
		  	overflow-y: scroll;
		  }
		  .result_space::-webkit-scrollbar {
			    width: 8px;
			}
			 
			.result_space::-webkit-scrollbar-track {
			    -webkit-box-shadow: inset 0 0 4px rgba(0,0,0,0.3);
			    border-radius: 6px;
			}
			 
			.result_space::-webkit-scrollbar-thumb {
			    border-radius: 6px;
			    -webkit-box-shadow: inset 0 0 4px rgba(0,0,0,0.5);
			}
		  
		  .close_button {
		  	display: block;
		  	height:26px;
		  	width: 26px;
		  	position: absolute;
		  	top: 0px;
		  	right: 10px;
		  	background-size: cover;
		  	background-position: center;
		  	background-image: url('/image/close.png');
		  }
		  .addnew {
		  	display:none;
		  	/*background-color: rgba(255,255,255,0.5);*/
		  }
		  .addnew_header {
		  	position: relative;
		  	height: 38px;
		  	/*border-bottom: double 5px;*/
		  }
		  .addnew_header p {
		  	margin-left: 10px;
		  }
		  
		  input {
		  	margin: 0;
			padding: 0;
			background: none;
			border: none;
			border-radius: 0;
			outline: none;
		  	-webkit-appearance: none;
			-moz-appearance: none;
			appearance: none;
		  }
		  input[type="text"] {
		  	display: block;
		  	border-bottom: solid 1px gray;
		  	width: 100%;
		  }
		  input[type="search"] {
		  	display: block;
		  	width: 100%;
		  }
		  .submit_button {
		  	position: absolute;
		  	bottom: 5px;
			display: block;
			text-align: center;
			line-height: 38px;
			width: 75%;
			height: 38px;
			border: solid 2px;
			/*background-color: white;*/
			/*border-radius: 10px;*/
			outline: none;
		}
		  
		  .addnew_button {
		  	display: block;
		  	position: absolute;
		  	width: 80%;
		  	height: 40px;
		  	line-height:34px;
		  	text-align: center;
		  	bottom: 10px;
		  	left: 10%;
		  	border: solid 1px blue;
		  	padding: 3px;
		  	color: blue;
		  	/*overflow: scroll;*/
		  	/*background-color: white;*/
		  }
		  .gdtitle {
		  	margin-bottom: 5px;
		  }
		  .datestr {
		  	position: absolute;
		  	right: 0;
		  	bottom: 0;
		  }
		  .gddata {
		  	padding: 5px;
		  	margin-bottom: 5px;
		  	border-top: solid 1px;
		  	position: relative;
		  }
		  input[type="number"] {
		  	width: 50px;
		  	text-align: center;
		  	padding-bottom: 5px;
		  	border-bottom: solid 1px gray;
		  }
		  .create_caution {
		  	margin-top: 5px;
		  	text-align: center;
		  	height: 20px;
		  	width: 95%;
		  	line-height: 20px;
		  	background-color: black;
		  	color: white;
		  }
		  .create_result {
		  	padding: 5px;
		  	border: solid 2px;
		  	height: 50px;
		  	width: 95%;
		  	/*overflow-y: scroll;*/
		  }
		  
		  .contents {
		  	height: 400px;
		  	background-color: rgba(255,255,255,0.7);
		  }
		  
		  /*.result_space .for_search {*/
		  /*	display:none;*/
		  /*}*/
		  .desc {
		  	text-align: center;
		  }
		  .glyphicon-heart {
		  	color: pink;
		  }
		</style>
		    <div class="space searching">
		    	<div class="search">
		    		<form name="search_form" id="search_form">
		    			<input type="search" name="searchWord" placeholder="キーワード/渡す相手から検索">
		    		</form>
		    		<a class="search_button" href="javascript:void(0)"></a>
		    	</div>
		    	<div class="result_space for_search">
		    		<div class="result">
		    			<div class="desc">
		    				<h4><i class="glyphicon glyphicon-heart"></i><i class="glyphicon glyphicon-heart"></i><i class="glyphicon glyphicon-heart"></i></h4>
		    				<p>素敵な日に<BR>素敵なプレゼントを渡しましょう。</p>
		    				<p>ここではプレゼントの日、<BR>カドゥ・ジュール/Cadeau jour<BR>を検索できます。</p>
		    				<p>キーワードや<BR>プレゼントを渡す相手<BR>から探すことができます。</p>
		    				<p>また、新しいカドゥ・ジュールを<BR>登録することもできます。</p>
		    				<h4><i class="glyphicon glyphicon-heart"></i><i class="glyphicon glyphicon-heart"></i><i class="glyphicon glyphicon-heart"></i></h4>
		    			</div>
		    		</div>
		    	</div>
		    </div>
		    <div class="space addnew">
		    	<div class="addnew_header">
		    		<a class="close_button" href="javascript:void(0)"></a>
		    	</div>
		    	<div class="result_space">
			    	<form name="create_form" id="create_form">
			    		<label>名称<span id="dncheck"></span>：<br><input id="dayName" type="text" name="dayName" placeholder="バレンタインデー"></label><BR>
			    		<label>プレゼントを渡す相手<span id="fwcheck"></span>：<br><input id="forWhom" type="text" name="forWhom" placeholder="恋人"></label><BR>
				    	<label>日付<span id="datecheck"></span>：<br><input id="month" type="number" name="month" placeholder="2">月</label><BR>
				    	<label><input id="day" type="number" name="day" placeholder="14">日</label>
			    	</form>
			    	<div class="create_caution"><i class="glyphicon glyphicon-info-sign"></i></div>
			    	<div class="create_result"></div>
			    	<a class="submit_button" href="javascript:void(0)"><i class="glyphicon glyphicon-ok-circle"></i>送信</a>
			    </div>
		    </div>
		    <a class="addnew_button" href="javascript:void(0)">+ 新しいカドゥ・ジュールを追加する</a>
		    
		    
		    
		    
		    
		    
		    
		    

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Month:</strong>
  <%= @calendar.month %>
</p>

<p>
  <strong>Day:</strong>
  <%= @calendar.day %>
</p>

<p>
  <strong>Name1:</strong>
  <%= @calendar.name1 %>
</p>

<p>
  <strong>Name2:</strong>
  <%= @calendar.name2 %>
</p>

<p>
  <strong>Name3:</strong>
  <%= @calendar.name3 %>
</p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>