config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :infos do
    member {get :img}
  end
  resources :calendars
  resources :gifts do
    member {get :img}
    member {get :eval}
  end
  resources :questions
  resources :anstoevals

  get '/admin' => 'welcome#admin'

  get '/qflow' => 'qflow#index'
  get '/qflow_continue' => 'qflow#continue'
  post '/result' => 'result#index'
  get '/result/countup' => 'result#countup'
  get '/result/countdown' => 'result#countdown'
  get '/result/countdown2' => 'result#countdown2'
  get '/new_arrival' => 'welcome#new'
  get '/info' => 'welcome#info'
  
  get '/calendar/getevent' => 'calendars#getevent'
  get '/calendar/search' => 'calendars#search'
  get '/calendar/ajaxcreate' => 'calendars#ajaxcreate'
  get '/calendar/daynameconf' => 'calendars#daynameconf'
  get '/calendar/nearday' => 'calendars#nearday'
  get '/calendar/search_bud' => 'calendars#search_bud'
  get '/calendar/search_flower' => 'calendars#search_flower'
  get '/calendar/eval' => 'calendars#eval'
  get '/calendar/get_calendar' => 'calendars#get_calendar'
  

  root 'welcome#index'
  
    post 'linebot/callback' => 'webhook#callback'
    post '/fbbot/callback' => 'fbmessenger#callback'

end

app/models/anstoeval.rb
class Anstoeval < ActiveRecord::Base
  belongs_to :answer
  belongs_to :evaluation
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :gift
end

app/models/fbtalk.rb
class Fbtalk < ActiveRecord::Base
end

app/models/gift.rb
class Gift < ActiveRecord::Base
    validates :name,
      presence: true,
      uniqueness: true
    validates :url,
      presence: true,
      uniqueness: true
    validates :img,
      presence: true
    validates :company_name,
      presence: true
    validates :price,
      presence: true
end

app/models/giftcalendar.rb
class Giftcalendar < ActiveRecord::Base
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
    validates :body,
      presence: true
end

app/models/talk.rb
class Talk < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy, :img]
  before_action :restrict_remote_ip, except: [:img]
  
  
  PERMIT_ADDRESSES = ['127.0.0.1', '::1', ENV['MY_IP_ADDRESS'], ENV['MY_SUB_IP_ADDRESS'], ENV['H_IP_ADDRESS']]

  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)
    #画像が登録されていなかったらid１の画像を設定する
    if params[:info][:img] !=nil
      @info.img = params[:info][:img].read # <= バイナリをセット
      @info.img_content_type = params[:info][:img].content_type # <= ファイルタイプをセット
    else
      @info.img = info.find(1).img
      @info.img_content_type = info.find(1).img_content_type
    end

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        if params[:info][:img] !=nil
          @info.update(:img => params[:info][:img].read) # <= バイナリをセット
          @info.update(:img_content_type => params[:info][:img].content_type) # <= ファイルタイプをセット
        else
          @info.update(:img => info.find(1).img) # <= バイナリをセット
          @info.update(:img_content_type => info.find(1).img_content_type) # <= ファイルタイプをセット
        end
        format.html { redirect_to @info, notice: 'info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def img
  send_data(@info.img, type: @info.img_content_type, disposition: :inline)
  end
  
  def eval
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:title,:content)
    end
    
    def restrict_remote_ip
    unless PERMIT_ADDRESSES.include?(request.remote_ip)
      render text: 'Service Unavailable', status: 503
    end
    end
end

app/helpers/anstoevals_helper.rb
module AnstoevalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/fbmessenger_helper.rb
module FbmessengerHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/qflow_helper.rb
module QflowHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :img %><br>
    <%= f.file_field :img %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Infos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Img</th>
      <th>Img content type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.title %></td>
        <td><%= info.content %></td>
        <td><%= image_tag(img_info_path(info), :height => "100px") %></td>
        <td><%= info.img_content_type %></td>
        <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New Info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @info.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @info.content %>
</p>

<p>
  <strong>Img:</strong>
  <%= image_tag(img_info_path(@info), :height => "100px") %>
</p>

<p>
  <strong>Img content type:</strong>
  <%= @info.img_content_type %>
</p>

<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>